spring.application.name=SortKut

spring.datasource.url=${DB_URL}

# Database Credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Multipart Upload Settings (1GB)
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1100MB

# Render Port Routing
server.port=${PORT:8080}
